name: Terraform CD

on:
  workflow_run:
    workflows:
      - Terraform CI
    types:
      - completed
concurrency: # controls how many GitHub Actions runs are allowed to work on the same thing at the same time. CD is the important place to prevent simultaneous deployments
  group: terraform-production
  cancel-in-progress: false # means don't cancel an existing deployment



permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  terraform-apply:
    name: Terraform Apply
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4 #this store artefact file of tfplan its download it and store
        with:
          name: terraform-plan
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::312977845460:role/GitHubActions-Terraform-Role
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan